@echo off
start https://youtu.be/W3q8Od5qJio?t=30
start https://youtu.be/CYiGyaJyPMk?t=14
start https://www.youtube.com/watch?v=gaMq-D7K8ls
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&t
start https://www.youtube.com/watch?v=cB4TUza4Fs0
start https://www.youtube.com/watch?v=Sf-sRscz7bY
start https://www.youtube.com/watch?v=-vyHIzlzlLQ
start https://www.youtube.com/watch?v=klr7-UxVino
start https://www.youtube.com/watch?v=P719ZYkrA3A